[package]
name = "dy-weekly-generator"
version = "0.1.0"
authors = ["codeworm96 <codeworm96@outlook.com>"]

[dependencies]
clap = {version = "2", features = ["yaml"]}
hyper = "0.9"
json = "0.11.0"
yaml-rust = "*"
