[package]
name = "dy-weekly-generator"
version = "0.2.0"
authors = ["codeworm96 <codeworm96@outlook.com>"]

[[bin]]
name = "weekly-gen"

[dependencies]
clap = {version = "2", features = ["yaml"]}
reqwest = "0.8"
json = "0.11"
yaml-rust = "0.4"
regex = "1.0"
