[package]
name = "dy-weekly-generator"
version = "0.3.4"
authors = ["codeworm96 <codeworm96@outlook.com>"]
edition = "2018"

[[bin]]
name = "weekly-gen"

[dependencies]
clap = "2.33"
reqwest = "0.9"
json = "0.12"
yaml-rust = "0.4"
regex = "1.3"
lazy_static = "1.4"
